EXPERIMENT_ROOT_PATH: "./experiments/"
EXPERIMENT_NAME: "jli3158"
DEVICE: "cuda"
TRAINING_SETTING:
  TRAIN_DIR_X: "../../database/trainB"
  TRAIN_DIR_Y: "../../database/trainB"
  NUM_EPOCHS: 15
  LAMBDA_Y: 1
  LEARNING_RATE: 0.00015
  BATCH_SIZE: 1
  NUM_WORKERS: 4
  SAVE_MODEL: true
  SAVE_MODEL_EPOCH_STEP: 1
  VISUALIZATION_STEP: 50
  LOAD_MODEL: false
  LOAD_EPOCH: 0
INFERENCE_SETTING:
  TEST_DIR_X: "../../database/Test"
  MODEL_VERSION: "latest"
  SAVE_ORIGINAL_IMAGE: True
